### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by diego191** [Vnet-as/postfwd-anti-geoip-spam-plugin#1]
Hello, would be possible to add support for PostgreSQL? 

It works a little if I modify database connection parameters. But it stops working after quite short time. I think the key problem is that autoreconnect for PostgreSQL is not implemented in Perl. 
I see following error in log:
postfwd2/policy[6588]: FATAL: Can't call method "errstr" on an undefined value at /etc/postfix/postfwd-anti-spam.plugin line 172, <STDIN> line 28.?

**Comment by Lirt** [comment]
Hello Diego,

I will look at this issue and fix it during this week. Thank you for reporting.

**Comment by Lirt** [comment]
Hello again Diego,

I pushed update where I resolved your issue by adding ping method on start of both postfwd functions. If ping is not successful, the database connection is renewed. Also I removed the autoconnect option, because it is working only for mysql.

You can test it now and if you have any other questions or you need advice on using the plugin, please feel free to write me email or open new issue.

**Comment by diego191** [comment]
Hi Ondrej, 
that works's perfectly! Thanks for your help.
