### ISSUE TITLE
Ip whitelisting

### ISSUE THREAD

**Issue by csazku** [Vnet-as/postfwd-anti-geoip-spam-plugin#50]
I'm using the plugin with postfwd3 2.02 with the following config

`id=COUNTRY_LOGIN_COUNT ; \
   sasl_username=~^(.+)$ ; \
   client_address=!!(x.x.x.x/x) ; \
   incr_client_country_login_count != 0 ; \
   action=jump(BAN_BOTNET)`

If my understanding of the sample config is correct **client_address=!!(x.x.x.x/x)** is a way to whitelist IPs, however postfwd runs plugins before the rules so the whitelisted IP gets added to the database and still counts toward **client_uniq_country_login_count** and **client_uniq_ip_login_count**

**Comment by Lirt** [comment]
Hi @csazku 

I will test if you are right, but from what you wrote, syntax `client_address=!!(x.x.x.x/x)` means that you are blacklisting CIDR, not whitelisting. So it means, you shouldn't have those IP addresses in database in the end.

**Comment by csazku** [comment]
The idea is that if an IP belongs to that CIDR it should not appear in the database.
Let me give you an example of what i mean: 
Let's say i want to block users who have logged in from more than 10 different IPs (**client_uniq_ip_login_count**) but some of them have their address set up as an alias in gmail. Almost every time these users send something it comes from a different IP so I'd like to stop any gsuite related ip from appearing in the database and tripping the uniq IP limit.
That's why I called it whitelisting.

**Comment by Lirt** [comment]
Okay, thanks for explanation, I got it now, I just looked at it from different point of view.

So I retested it and you are right, the plugin is processed before `postfwd` ruleset and the user with IP address is in any case incremented or created. 

Now I'm not sure if there is simple way to fix this issue since postfwd plugin mechanism won't change. 

What we can definitely do, is to add new configuration parameter - something like `cidr_whitelist` (IP address list, that will be skipped) and skip processing of the IP address inside of the plugin if it matches this `cidr_whitelist`.

**Comment by Lirt** [comment]
Okay, thanks for explanation, I got it now, I just looked at it from different point of view.

So I retested it and you are right, the plugin is processed before `postfwd` ruleset and the user with IP address is in any case incremented or created. 

Now I'm not sure if there is simple way to fix this issue since postfwd plugin mechanism won't change. 

What we can definitely do, is to add new configuration parameter - something like `cidr_whitelist` (IP address list, that will be skipped) and skip processing of the IP address inside of the plugin if it matches this `cidr_whitelist`.

**Comment by csazku** [comment]
Yes, that works for me.
To add to your idea maybe instead of having the IPs in `cidr_whitelist` the parameter should contain the path to a file that contains the IP list and supports comments, if it's not too much trouble to make. The base postfwd already has a function like this ( [https://postfwd.org/doc.html#FILES](https://postfwd.org/doc.html#FILES) )

**Comment by Lirt** [comment]
@csazku Please review the PR at least optically and let me know if it fits you https://github.com/Vnet-as/postfwd-anti-geoip-spam-plugin/pull/51

I will do some more tests and update the testing suite later on to make sure everything works well.

It will be released in `1.40` after merge.

**Comment by csazku** [comment]
Did a quick test on a development mail server, seems to be working well.
As a side note:
`id=COUNTRY_LOGIN_COUNT ;
   sasl_username=~^(.+)$ ;
   incr_client_country_login_count != 0 ;
   action=dunno ;`
This rule can be removed from the conf since `incr_client_country_login_count` gets calculated anyway.

**Comment by Lirt** [comment]
That's right. Done.

**Comment by Lirt** [comment]
Implemented and Closed in https://github.com/Vnet-as/postfwd-anti-geoip-spam-plugin/pull/51

**Comment by Lirt** [comment]
@csazku you can use tag `v1.40` also available on [dockerhub](https://hub.docker.com/r/lirt/postfwd-anti-geoip-spam-plugin)
